name: Tag nightly

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for new release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ${GITHUB_WORKSPACE}/.github/scripts/update-ghostty.sh

      - name: Update nightly tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push --delete origin tip
          git tag -fa tip -m "Nightly build"
          git push origin tip
